# Form implementation generated from reading ui file 'D:\UEL-2025-2026-HK1\TUDUYLAPTRINH\Team_Work_GitHub_Tu_duy_lap_trinh_GitHub\MainWindow.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1141, 753)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 1141, 101))
        self.label.setStyleSheet("font: 24pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 0, 255);\n"
"background-color: rgb(255, 255, 0);")
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(30, 150, 111, 51))
        self.label_2.setStyleSheet("font: 16pt \"MS Shell Dlg 2\";")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(30, 250, 111, 51))
        self.label_3.setStyleSheet("font: 16pt \"MS Shell Dlg 2\";")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(30, 350, 111, 51))
        self.label_4.setStyleSheet("font: 16pt \"MS Shell Dlg 2\";")
        self.label_4.setObjectName("label_4")
        self.lineEditA = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEditA.setGeometry(QtCore.QRect(180, 150, 721, 61))
        self.lineEditA.setStyleSheet("font: 16pt \"MS Shell Dlg 2\";")
        self.lineEditA.setObjectName("lineEditA")
        self.lineEditB = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEditB.setGeometry(QtCore.QRect(180, 250, 721, 61))
        self.lineEditB.setStyleSheet("font: 16pt \"MS Shell Dlg 2\";")
        self.lineEditB.setObjectName("lineEditB")
        self.lineEditC = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEditC.setGeometry(QtCore.QRect(180, 350, 721, 61))
        self.lineEditC.setStyleSheet("font: 16pt \"MS Shell Dlg 2\";")
        self.lineEditC.setObjectName("lineEditC")
        self.label_5 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(20, 530, 111, 51))
        self.label_5.setStyleSheet("font: 16pt \"MS Shell Dlg 2\";")
        self.label_5.setObjectName("label_5")
        self.lineEditResult = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEditResult.setGeometry(QtCore.QRect(180, 520, 721, 61))
        self.lineEditResult.setStyleSheet("font: 16pt \"MS Shell Dlg 2\";")
        self.lineEditResult.setObjectName("lineEditResult")
        self.pushButtonSolve = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonSolve.setGeometry(QtCore.QRect(220, 450, 93, 41))
        self.pushButtonSolve.setStyleSheet("font: 16pt \"MS Shell Dlg 2\";")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("D:\\UEL-2025-2026-HK1\\TUDUYLAPTRINH\\Team_Work_GitHub_Tu_duy_lap_trinh_GitHub\\../sales_report/images/calculate.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonSolve.setIcon(icon)
        self.pushButtonSolve.setObjectName("pushButtonSolve")
        self.pushButtonClear = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonClear.setGeometry(QtCore.QRect(420, 450, 93, 41))
        self.pushButtonClear.setStyleSheet("font: 16pt \"MS Shell Dlg 2\";")
        self.pushButtonClear.setObjectName("pushButtonClear")
        self.pushButtonClose = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonClose.setGeometry(QtCore.QRect(640, 450, 101, 41))
        self.pushButtonClose.setStyleSheet("font: 16pt \"MS Shell Dlg 2\";")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("D:\\UEL-2025-2026-HK1\\TUDUYLAPTRINH\\Team_Work_GitHub_Tu_duy_lap_trinh_GitHub\\../learn_gui/fibo_gui/images/close.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonClose.setIcon(icon1)
        self.pushButtonClose.setObjectName("pushButtonClose")
        self.labelImage = QtWidgets.QLabel(parent=self.centralwidget)
        self.labelImage.setGeometry(QtCore.QRect(930, 160, 181, 421))
        self.labelImage.setText("")
        self.labelImage.setPixmap(QtGui.QPixmap("C:/Users/DELL/Pictures/ip11/IMG_6278.JPG"))
        self.labelImage.setScaledContents(True)
        self.labelImage.setObjectName("labelImage")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1141, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.pushButtonClear.clicked.connect(self.lineEditA.clear) # type: ignore
        self.pushButtonClear.clicked.connect(self.lineEditB.clear) # type: ignore
        self.pushButtonClear.clicked.connect(self.lineEditC.clear) # type: ignore
        self.pushButtonClear.clicked.connect(self.lineEditResult.clear) # type: ignore
        self.pushButtonClose.clicked.connect(MainWindow.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Quadratic Equation"))
        self.label_2.setText(_translate("MainWindow", "A Coeff:"))
        self.label_3.setText(_translate("MainWindow", "B Coeff:"))
        self.label_4.setText(_translate("MainWindow", "C Coeff:"))
        self.label_5.setText(_translate("MainWindow", "Result:"))
        self.pushButtonSolve.setText(_translate("MainWindow", "Solve"))
        self.pushButtonClear.setText(_translate("MainWindow", "Clear"))
        self.pushButtonClose.setText(_translate("MainWindow", "Close"))
